eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/
spring:
  application:
    name: springcloud-client
server:
  port: 8085
userinfo:
  username: liuxiaoyu
  password: liuxiaoyu
  
